"try:
    self._task.post_validate(templar=templar)
except AnsibleError:
    raise
except Exception:
    return dict(changed=False, failed=True, _ansible_no_log=self._play_context.no_log, exception=to_text(traceback.format_exc()))
"
-------------------------------------------------------------------------
"try:
    self._task.post_validate(templar=templar)
except AnsibleError:
    raise
except Exception:
    return dict(changed=False, failed=True, _ansible_no_log=self._play_context.no_log, exception=to_text(traceback.format_exc()))
"
-------------------------------------------------------------------------
"try:
    self._task.post_validate(templar=templar)
except AnsibleError:
    raise
except Exception:
    return dict(changed=False, failed=True, _ansible_no_log=self._play_context.no_log, exception=to_text(traceback.format_exc()))
"
-------------------------------------------------------------------------
""
-------------------------------------------------------------------------
=========================================================================
